package auth

import (
	"testing"
)

func TestPasswordHashing(t *testing.T) {
	password := "password"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	if !VerifyPassword(password, hash) {
		t.Fatalf("VerifyPassword failed to verify freshly hashed password")
	}

	if VerifyPassword("wrong-password", hash) {
		t.Fatalf("VerifyPassword accepted incorrect password")
	}
}

func TestNodeCompatibility(t *testing.T) {
	// Hash generated by Node's scrypt for "password"
	nodeHash := "1373f1cb410d1e7c132150e5db136d38:b72c05c919f923952d773f58ab359add0e75df09be6a8668cff6a87e5e01042a978807630b7619c3afa0281d146140f7cdb40e8dc9600062b702f723ed8ab7ba"
	if !VerifyPassword("password", nodeHash) {
		t.Fatalf("VerifyPassword failed to verify Node.js scrypt hash")
	}
}
