// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO "Session" (id, "userId", "expiresAt")
VALUES ($1, $2, $3)
RETURNING id, "userId", "expiresAt", "createdAt"
`

type CreateSessionParams struct {
	ID        string           `json:"id"`
	UserId    string           `json:"userId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserId, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" (id, email, name, color, "avatarUrl", "passwordHash")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, color, "avatarUrl", "createdAt", "passwordHash"
`

type CreateUserParams struct {
	ID           string      `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Color        string      `json:"color"`
	AvatarUrl    pgtype.Text `json:"avatarUrl"`
	PasswordHash pgtype.Text `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Color,
		arg.AvatarUrl,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Color,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM "Session"
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.id, s."userId", s."expiresAt", s."createdAt",
       u.id as user_id, u.email as user_email, u.name as user_name, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "Session" s
JOIN "User" u ON s."userId" = u.id
WHERE s.id = $1 AND s."expiresAt" > NOW()
LIMIT 1
`

type GetSessionWithUserRow struct {
	ID            string           `json:"id"`
	UserId        string           `json:"userId"`
	ExpiresAt     pgtype.Timestamp `json:"expiresAt"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UserID        string           `json:"user_id"`
	UserEmail     string           `json:"user_email"`
	UserName      string           `json:"user_name"`
	UserColor     string           `json:"user_color"`
	UserAvatarUrl pgtype.Text      `json:"user_avatar_url"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.UserColor,
		&i.UserAvatarUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, color, "avatarUrl", "createdAt", "passwordHash"
FROM "User"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Color,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, color, "avatarUrl", "createdAt", "passwordHash"
FROM "User"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Color,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserMembership = `-- name: GetUserMembership :one
SELECT wm.id, wm."workspaceId", wm."userId", wm.role, wm."createdAt"
FROM "WorkspaceMember" wm
WHERE wm."userId" = $1
ORDER BY wm."createdAt" ASC
LIMIT 1
`

func (q *Queries) GetUserMembership(ctx context.Context, userid string) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getUserMembership, userid)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.UserId,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, color, "avatarUrl", "createdAt"
FROM "User"
ORDER BY name ASC
`

type ListUsersRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	Color     string           `json:"color"`
	AvatarUrl pgtype.Text      `json:"avatarUrl"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Color,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "User"
SET name = COALESCE($2, name),
    color = COALESCE($3, color),
    "avatarUrl" = COALESCE($4, "avatarUrl")
WHERE id = $1
RETURNING id, email, name, color, "avatarUrl", "createdAt", "passwordHash"
`

type UpdateUserParams struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	AvatarUrl pgtype.Text `json:"avatarUrl"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Color,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}
