// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklists.sql

package db

import (
	"context"
)

const createChecklist = `-- name: CreateChecklist :one
INSERT INTO "Checklist" (id, "taskId", name, "position")
VALUES ($1, $2, $3, $4)
RETURNING id, "taskId", name, "position"
`

type CreateChecklistParams struct {
	ID       string  `json:"id"`
	TaskId   string  `json:"taskId"`
	Name     string  `json:"name"`
	Position float64 `json:"position"`
}

func (q *Queries) CreateChecklist(ctx context.Context, arg CreateChecklistParams) (Checklist, error) {
	row := q.db.QueryRow(ctx, createChecklist,
		arg.ID,
		arg.TaskId,
		arg.Name,
		arg.Position,
	)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO "ChecklistItem" (id, "checklistId", name, resolved, "position")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "checklistId", name, resolved, "position"
`

type CreateChecklistItemParams struct {
	ID          string  `json:"id"`
	ChecklistId string  `json:"checklistId"`
	Name        string  `json:"name"`
	Resolved    bool    `json:"resolved"`
	Position    float64 `json:"position"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem,
		arg.ID,
		arg.ChecklistId,
		arg.Name,
		arg.Resolved,
		arg.Position,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistId,
		&i.Name,
		&i.Resolved,
		&i.Position,
	)
	return i, err
}

const deleteChecklist = `-- name: DeleteChecklist :exec
DELETE FROM "Checklist" WHERE id = $1
`

func (q *Queries) DeleteChecklist(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChecklist, id)
	return err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM "ChecklistItem" WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChecklistItem, id)
	return err
}

const getChecklistByID = `-- name: GetChecklistByID :one
SELECT id, "taskId", name, "position"
FROM "Checklist"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChecklistByID(ctx context.Context, id string) (Checklist, error) {
	row := q.db.QueryRow(ctx, getChecklistByID, id)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, "checklistId", name, resolved, "position"
FROM "ChecklistItem"
WHERE "checklistId" = $1
ORDER BY "position" ASC
`

func (q *Queries) ListChecklistItems(ctx context.Context, checklistid string) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, checklistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistId,
			&i.Name,
			&i.Resolved,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistsByTask = `-- name: ListChecklistsByTask :many
SELECT id, "taskId", name, "position"
FROM "Checklist"
WHERE "taskId" = $1
ORDER BY "position" ASC
`

func (q *Queries) ListChecklistsByTask(ctx context.Context, taskid string) ([]Checklist, error) {
	rows, err := q.db.Query(ctx, listChecklistsByTask, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checklist{}
	for rows.Next() {
		var i Checklist
		if err := rows.Scan(
			&i.ID,
			&i.TaskId,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChecklist = `-- name: UpdateChecklist :one
UPDATE "Checklist"
SET name = COALESCE($2, name),
    "position" = COALESCE($3, "position")
WHERE id = $1
RETURNING id, "taskId", name, "position"
`

type UpdateChecklistParams struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Position float64 `json:"position"`
}

func (q *Queries) UpdateChecklist(ctx context.Context, arg UpdateChecklistParams) (Checklist, error) {
	row := q.db.QueryRow(ctx, updateChecklist, arg.ID, arg.Name, arg.Position)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE "ChecklistItem"
SET name = COALESCE($2, name),
    resolved = COALESCE($3, resolved),
    "position" = COALESCE($4, "position")
WHERE id = $1
RETURNING id, "checklistId", name, resolved, "position"
`

type UpdateChecklistItemParams struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Resolved bool    `json:"resolved"`
	Position float64 `json:"position"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.ID,
		arg.Name,
		arg.Resolved,
		arg.Position,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistId,
		&i.Name,
		&i.Resolved,
		&i.Position,
	)
	return i, err
}
