// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :one
INSERT INTO "CommentReaction" (id, "commentId", "userId", emoji)
VALUES ($1, $2, $3, $4)
RETURNING id, "commentId", "userId", emoji
`

type AddReactionParams struct {
	ID        string `json:"id"`
	CommentId string `json:"commentId"`
	UserId    string `json:"userId"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (CommentReaction, error) {
	row := q.db.QueryRow(ctx, addReaction,
		arg.ID,
		arg.CommentId,
		arg.UserId,
		arg.Emoji,
	)
	var i CommentReaction
	err := row.Scan(
		&i.ID,
		&i.CommentId,
		&i.UserId,
		&i.Emoji,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO "Comment" (id, "taskId", "userId", body, "parentId", "updatedAt")
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, "taskId", "userId", body, "parentId", resolved, "createdAt", "updatedAt"
`

type CreateCommentParams struct {
	ID       string      `json:"id"`
	TaskId   string      `json:"taskId"`
	UserId   string      `json:"userId"`
	Body     string      `json:"body"`
	ParentId pgtype.Text `json:"parentId"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.TaskId,
		arg.UserId,
		arg.Body,
		arg.ParentId,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.UserId,
		&i.Body,
		&i.ParentId,
		&i.Resolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM "Comment" WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, "taskId", "userId", body, "parentId", resolved, "createdAt", "updatedAt"
FROM "Comment"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCommentByID(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.UserId,
		&i.Body,
		&i.ParentId,
		&i.Resolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT c.id, c."taskId", c."userId", c.body, c."parentId", c.resolved, c."createdAt", c."updatedAt",
       u.name as user_name, u.email as user_email, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "Comment" c
JOIN "User" u ON c."userId" = u.id
WHERE c."taskId" = $1
ORDER BY c."createdAt" ASC
`

type ListCommentsByTaskRow struct {
	ID            string           `json:"id"`
	TaskId        string           `json:"taskId"`
	UserId        string           `json:"userId"`
	Body          string           `json:"body"`
	ParentId      pgtype.Text      `json:"parentId"`
	Resolved      bool             `json:"resolved"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	UserName      string           `json:"user_name"`
	UserEmail     string           `json:"user_email"`
	UserColor     string           `json:"user_color"`
	UserAvatarUrl pgtype.Text      `json:"user_avatar_url"`
}

func (q *Queries) ListCommentsByTask(ctx context.Context, taskid string) ([]ListCommentsByTaskRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByTask, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByTaskRow{}
	for rows.Next() {
		var i ListCommentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskId,
			&i.UserId,
			&i.Body,
			&i.ParentId,
			&i.Resolved,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserColor,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByComment = `-- name: ListReactionsByComment :many
SELECT cr.id, cr."commentId", cr."userId", cr.emoji,
       u.name as user_name
FROM "CommentReaction" cr
JOIN "User" u ON cr."userId" = u.id
WHERE cr."commentId" = $1
`

type ListReactionsByCommentRow struct {
	ID        string `json:"id"`
	CommentId string `json:"commentId"`
	UserId    string `json:"userId"`
	Emoji     string `json:"emoji"`
	UserName  string `json:"user_name"`
}

func (q *Queries) ListReactionsByComment(ctx context.Context, commentid string) ([]ListReactionsByCommentRow, error) {
	rows, err := q.db.Query(ctx, listReactionsByComment, commentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByCommentRow{}
	for rows.Next() {
		var i ListReactionsByCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.CommentId,
			&i.UserId,
			&i.Emoji,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM "CommentReaction"
WHERE "commentId" = $1 AND "userId" = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	CommentId string `json:"commentId"`
	UserId    string `json:"userId"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.CommentId, arg.UserId, arg.Emoji)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE "Comment"
SET body = COALESCE($2, body),
    resolved = COALESCE($3, resolved),
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "taskId", "userId", body, "parentId", resolved, "createdAt", "updatedAt"
`

type UpdateCommentParams struct {
	ID       string `json:"id"`
	Body     string `json:"body"`
	Resolved bool   `json:"resolved"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Body, arg.Resolved)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.UserId,
		&i.Body,
		&i.ParentId,
		&i.Resolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
