// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoc = `-- name: CreateDoc :one
INSERT INTO "Doc" (id, workspace_id, space_id, folder_id, list_id, task_id, title, created_by_id, is_pinned)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, workspace_id, space_id, folder_id, list_id, task_id, title, created_by_id, is_pinned, created_at, updated_at
`

type CreateDocParams struct {
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	SpaceID     pgtype.Text `json:"space_id"`
	FolderID    pgtype.Text `json:"folder_id"`
	ListID      pgtype.Text `json:"list_id"`
	TaskID      pgtype.Text `json:"task_id"`
	Title       string      `json:"title"`
	CreatedByID string      `json:"created_by_id"`
	IsPinned    bool        `json:"is_pinned"`
}

func (q *Queries) CreateDoc(ctx context.Context, arg CreateDocParams) (Doc, error) {
	row := q.db.QueryRow(ctx, createDoc,
		arg.ID,
		arg.WorkspaceID,
		arg.SpaceID,
		arg.FolderID,
		arg.ListID,
		arg.TaskID,
		arg.Title,
		arg.CreatedByID,
		arg.IsPinned,
	)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SpaceID,
		&i.FolderID,
		&i.ListID,
		&i.TaskID,
		&i.Title,
		&i.CreatedByID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocPage = `-- name: CreateDocPage :one
INSERT INTO "DocPage" (id, doc_id, parent_page_id, title, content_markdown, content_html, icon, cover_image, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, doc_id, parent_page_id, title, content_markdown, content_html, icon, cover_image, position, created_at, updated_at
`

type CreateDocPageParams struct {
	ID              string      `json:"id"`
	DocID           string      `json:"doc_id"`
	ParentPageID    pgtype.Text `json:"parent_page_id"`
	Title           string      `json:"title"`
	ContentMarkdown string      `json:"content_markdown"`
	ContentHtml     string      `json:"content_html"`
	Icon            pgtype.Text `json:"icon"`
	CoverImage      pgtype.Text `json:"cover_image"`
	Position        float64     `json:"position"`
}

func (q *Queries) CreateDocPage(ctx context.Context, arg CreateDocPageParams) (DocPage, error) {
	row := q.db.QueryRow(ctx, createDocPage,
		arg.ID,
		arg.DocID,
		arg.ParentPageID,
		arg.Title,
		arg.ContentMarkdown,
		arg.ContentHtml,
		arg.Icon,
		arg.CoverImage,
		arg.Position,
	)
	var i DocPage
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.ParentPageID,
		&i.Title,
		&i.ContentMarkdown,
		&i.ContentHtml,
		&i.Icon,
		&i.CoverImage,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoc = `-- name: DeleteDoc :exec
DELETE FROM "Doc" WHERE id = $1
`

func (q *Queries) DeleteDoc(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDoc, id)
	return err
}

const deleteDocPage = `-- name: DeleteDocPage :exec
DELETE FROM "DocPage" WHERE id = $1
`

func (q *Queries) DeleteDocPage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDocPage, id)
	return err
}

const getDocByID = `-- name: GetDocByID :one
SELECT id, workspace_id, space_id, folder_id, list_id, task_id, title, created_by_id, is_pinned, created_at, updated_at FROM "Doc" WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocByID(ctx context.Context, id string) (Doc, error) {
	row := q.db.QueryRow(ctx, getDocByID, id)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SpaceID,
		&i.FolderID,
		&i.ListID,
		&i.TaskID,
		&i.Title,
		&i.CreatedByID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocPageByID = `-- name: GetDocPageByID :one
SELECT id, doc_id, parent_page_id, title, content_markdown, content_html, icon, cover_image, position, created_at, updated_at FROM "DocPage" WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocPageByID(ctx context.Context, id string) (DocPage, error) {
	row := q.db.QueryRow(ctx, getDocPageByID, id)
	var i DocPage
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.ParentPageID,
		&i.Title,
		&i.ContentMarkdown,
		&i.ContentHtml,
		&i.Icon,
		&i.CoverImage,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocPagesByDocID = `-- name: ListDocPagesByDocID :many
SELECT id, doc_id, parent_page_id, title, icon, cover_image, position, created_at, updated_at
FROM "DocPage"
WHERE doc_id = $1
ORDER BY position ASC, created_at ASC
`

type ListDocPagesByDocIDRow struct {
	ID           string             `json:"id"`
	DocID        string             `json:"doc_id"`
	ParentPageID pgtype.Text        `json:"parent_page_id"`
	Title        string             `json:"title"`
	Icon         pgtype.Text        `json:"icon"`
	CoverImage   pgtype.Text        `json:"cover_image"`
	Position     float64            `json:"position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDocPagesByDocID(ctx context.Context, docID string) ([]ListDocPagesByDocIDRow, error) {
	rows, err := q.db.Query(ctx, listDocPagesByDocID, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocPagesByDocIDRow{}
	for rows.Next() {
		var i ListDocPagesByDocIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.ParentPageID,
			&i.Title,
			&i.Icon,
			&i.CoverImage,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsBySpace = `-- name: ListDocsBySpace :many
SELECT d.id, d.workspace_id, d.space_id, d.folder_id, d.list_id, d.task_id, d.title, d.created_by_id, d.is_pinned, d.created_at, d.updated_at, u.name as creator_name, u.email as creator_email, u.color as creator_color, u."avatarUrl" as creator_avatar_url
FROM "Doc" d
JOIN "User" u ON d.created_by_id = u.id
WHERE d.space_id = $1
ORDER BY d.updated_at DESC
`

type ListDocsBySpaceRow struct {
	ID               string             `json:"id"`
	WorkspaceID      string             `json:"workspace_id"`
	SpaceID          pgtype.Text        `json:"space_id"`
	FolderID         pgtype.Text        `json:"folder_id"`
	ListID           pgtype.Text        `json:"list_id"`
	TaskID           pgtype.Text        `json:"task_id"`
	Title            string             `json:"title"`
	CreatedByID      string             `json:"created_by_id"`
	IsPinned         bool               `json:"is_pinned"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorName      string             `json:"creator_name"`
	CreatorEmail     string             `json:"creator_email"`
	CreatorColor     string             `json:"creator_color"`
	CreatorAvatarUrl pgtype.Text        `json:"creator_avatar_url"`
}

func (q *Queries) ListDocsBySpace(ctx context.Context, spaceID pgtype.Text) ([]ListDocsBySpaceRow, error) {
	rows, err := q.db.Query(ctx, listDocsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsBySpaceRow{}
	for rows.Next() {
		var i ListDocsBySpaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SpaceID,
			&i.FolderID,
			&i.ListID,
			&i.TaskID,
			&i.Title,
			&i.CreatedByID,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
			&i.CreatorEmail,
			&i.CreatorColor,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsByWorkspace = `-- name: ListDocsByWorkspace :many
SELECT d.id, d.workspace_id, d.space_id, d.folder_id, d.list_id, d.task_id, d.title, d.created_by_id, d.is_pinned, d.created_at, d.updated_at, u.name as creator_name, u.email as creator_email, u.color as creator_color, u."avatarUrl" as creator_avatar_url
FROM "Doc" d
JOIN "User" u ON d.created_by_id = u.id
WHERE d.workspace_id = $1
ORDER BY d.updated_at DESC
`

type ListDocsByWorkspaceRow struct {
	ID               string             `json:"id"`
	WorkspaceID      string             `json:"workspace_id"`
	SpaceID          pgtype.Text        `json:"space_id"`
	FolderID         pgtype.Text        `json:"folder_id"`
	ListID           pgtype.Text        `json:"list_id"`
	TaskID           pgtype.Text        `json:"task_id"`
	Title            string             `json:"title"`
	CreatedByID      string             `json:"created_by_id"`
	IsPinned         bool               `json:"is_pinned"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorName      string             `json:"creator_name"`
	CreatorEmail     string             `json:"creator_email"`
	CreatorColor     string             `json:"creator_color"`
	CreatorAvatarUrl pgtype.Text        `json:"creator_avatar_url"`
}

func (q *Queries) ListDocsByWorkspace(ctx context.Context, workspaceID string) ([]ListDocsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listDocsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocsByWorkspaceRow{}
	for rows.Next() {
		var i ListDocsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SpaceID,
			&i.FolderID,
			&i.ListID,
			&i.TaskID,
			&i.Title,
			&i.CreatedByID,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
			&i.CreatorEmail,
			&i.CreatorColor,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoc = `-- name: UpdateDoc :one
UPDATE "Doc"
SET title = COALESCE($1, title),
    is_pinned = COALESCE($2, is_pinned),
    space_id = COALESCE($3, space_id),
    folder_id = COALESCE($4, folder_id),
    list_id = COALESCE($5, list_id),
    updated_at = NOW()
WHERE id = $6
RETURNING id, workspace_id, space_id, folder_id, list_id, task_id, title, created_by_id, is_pinned, created_at, updated_at
`

type UpdateDocParams struct {
	Title    pgtype.Text `json:"title"`
	IsPinned pgtype.Bool `json:"is_pinned"`
	SpaceID  pgtype.Text `json:"space_id"`
	FolderID pgtype.Text `json:"folder_id"`
	ListID   pgtype.Text `json:"list_id"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdateDoc(ctx context.Context, arg UpdateDocParams) (Doc, error) {
	row := q.db.QueryRow(ctx, updateDoc,
		arg.Title,
		arg.IsPinned,
		arg.SpaceID,
		arg.FolderID,
		arg.ListID,
		arg.ID,
	)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SpaceID,
		&i.FolderID,
		&i.ListID,
		&i.TaskID,
		&i.Title,
		&i.CreatedByID,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocPage = `-- name: UpdateDocPage :one
UPDATE "DocPage"
SET title = COALESCE($1, title),
    content_markdown = COALESCE($2, content_markdown),
    content_html = COALESCE($3, content_html),
    icon = COALESCE($4, icon),
    cover_image = COALESCE($5, cover_image),
    position = COALESCE($6, position),
    parent_page_id = COALESCE($7, parent_page_id),
    updated_at = NOW()
WHERE id = $8
RETURNING id, doc_id, parent_page_id, title, content_markdown, content_html, icon, cover_image, position, created_at, updated_at
`

type UpdateDocPageParams struct {
	Title           pgtype.Text   `json:"title"`
	ContentMarkdown pgtype.Text   `json:"content_markdown"`
	ContentHtml     pgtype.Text   `json:"content_html"`
	Icon            pgtype.Text   `json:"icon"`
	CoverImage      pgtype.Text   `json:"cover_image"`
	Position        pgtype.Float8 `json:"position"`
	ParentPageID    pgtype.Text   `json:"parent_page_id"`
	ID              string        `json:"id"`
}

func (q *Queries) UpdateDocPage(ctx context.Context, arg UpdateDocPageParams) (DocPage, error) {
	row := q.db.QueryRow(ctx, updateDocPage,
		arg.Title,
		arg.ContentMarkdown,
		arg.ContentHtml,
		arg.Icon,
		arg.CoverImage,
		arg.Position,
		arg.ParentPageID,
		arg.ID,
	)
	var i DocPage
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.ParentPageID,
		&i.Title,
		&i.ContentMarkdown,
		&i.ContentHtml,
		&i.Icon,
		&i.CoverImage,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
