// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CustomFieldType string

const (
	CustomFieldTypeTEXT     CustomFieldType = "TEXT"
	CustomFieldTypeTEXTAREA CustomFieldType = "TEXTAREA"
	CustomFieldTypeNUMBER   CustomFieldType = "NUMBER"
	CustomFieldTypeMONEY    CustomFieldType = "MONEY"
	CustomFieldTypeDROPDOWN CustomFieldType = "DROPDOWN"
	CustomFieldTypeLABELS   CustomFieldType = "LABELS"
	CustomFieldTypeDATE     CustomFieldType = "DATE"
	CustomFieldTypeCHECKBOX CustomFieldType = "CHECKBOX"
	CustomFieldTypeURL      CustomFieldType = "URL"
	CustomFieldTypeEMAIL    CustomFieldType = "EMAIL"
	CustomFieldTypePHONE    CustomFieldType = "PHONE"
	CustomFieldTypeRATING   CustomFieldType = "RATING"
	CustomFieldTypePROGRESS CustomFieldType = "PROGRESS"
)

func (e *CustomFieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomFieldType(s)
	case string:
		*e = CustomFieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomFieldType: %T", src)
	}
	return nil
}

type NullCustomFieldType struct {
	CustomFieldType CustomFieldType `json:"CustomFieldType"`
	Valid           bool            `json:"valid"` // Valid is true if CustomFieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.CustomFieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomFieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomFieldType), nil
}

type MemberRole string

const (
	MemberRoleOWNER  MemberRole = "OWNER"
	MemberRoleADMIN  MemberRole = "ADMIN"
	MemberRoleMEMBER MemberRole = "MEMBER"
	MemberRoleGUEST  MemberRole = "GUEST"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"MemberRole"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type Priority string

const (
	PriorityURGENT Priority = "URGENT"
	PriorityHIGH   Priority = "HIGH"
	PriorityNORMAL Priority = "NORMAL"
	PriorityLOW    Priority = "LOW"
)

func (e *Priority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priority(s)
	case string:
		*e = Priority(s)
	default:
		return fmt.Errorf("unsupported scan type for Priority: %T", src)
	}
	return nil
}

type NullPriority struct {
	Priority Priority `json:"Priority"`
	Valid    bool     `json:"valid"` // Valid is true if Priority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriority) Scan(value interface{}) error {
	if value == nil {
		ns.Priority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priority), nil
}

type StatusType string

const (
	StatusTypeNOTSTARTED StatusType = "NOT_STARTED"
	StatusTypeACTIVE     StatusType = "ACTIVE"
	StatusTypeDONE       StatusType = "DONE"
	StatusTypeCLOSED     StatusType = "CLOSED"
)

func (e *StatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusType(s)
	case string:
		*e = StatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusType: %T", src)
	}
	return nil
}

type NullStatusType struct {
	StatusType StatusType `json:"StatusType"`
	Valid      bool       `json:"valid"` // Valid is true if StatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusType), nil
}

type ViewType string

const (
	ViewTypeLIST     ViewType = "LIST"
	ViewTypeBOARD    ViewType = "BOARD"
	ViewTypeCALENDAR ViewType = "CALENDAR"
	ViewTypeGANTT    ViewType = "GANTT"
	ViewTypeTABLE    ViewType = "TABLE"
)

func (e *ViewType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ViewType(s)
	case string:
		*e = ViewType(s)
	default:
		return fmt.Errorf("unsupported scan type for ViewType: %T", src)
	}
	return nil
}

type NullViewType struct {
	ViewType ViewType `json:"ViewType"`
	Valid    bool     `json:"valid"` // Valid is true if ViewType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullViewType) Scan(value interface{}) error {
	if value == nil {
		ns.ViewType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ViewType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullViewType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ViewType), nil
}

type Activity struct {
	ID        string           `json:"id"`
	TaskId    string           `json:"taskId"`
	UserId    pgtype.Text      `json:"userId"`
	Type      string           `json:"type"`
	Data      []byte           `json:"data"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Attachment struct {
	ID           string           `json:"id"`
	TaskId       string           `json:"taskId"`
	Name         string           `json:"name"`
	Url          string           `json:"url"`
	Size         int32            `json:"size"`
	Mime         string           `json:"mime"`
	UploadedById pgtype.Text      `json:"uploadedById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type Checklist struct {
	ID       string  `json:"id"`
	TaskId   string  `json:"taskId"`
	Name     string  `json:"name"`
	Position float64 `json:"position"`
}

type ChecklistItem struct {
	ID          string  `json:"id"`
	ChecklistId string  `json:"checklistId"`
	Name        string  `json:"name"`
	Resolved    bool    `json:"resolved"`
	Position    float64 `json:"position"`
}

type Comment struct {
	ID        string           `json:"id"`
	TaskId    string           `json:"taskId"`
	UserId    string           `json:"userId"`
	Body      string           `json:"body"`
	ParentId  pgtype.Text      `json:"parentId"`
	Resolved  bool             `json:"resolved"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type CommentReaction struct {
	ID        string `json:"id"`
	CommentId string `json:"commentId"`
	UserId    string `json:"userId"`
	Emoji     string `json:"emoji"`
}

type CustomField struct {
	ID       string          `json:"id"`
	ListId   string          `json:"listId"`
	Name     string          `json:"name"`
	Type     CustomFieldType `json:"type"`
	Config   []byte          `json:"config"`
	Position float64         `json:"position"`
}

type CustomFieldOption struct {
	ID            string  `json:"id"`
	CustomFieldId string  `json:"customFieldId"`
	Label         string  `json:"label"`
	Color         string  `json:"color"`
	Position      float64 `json:"position"`
}

type CustomFieldValue struct {
	ID            string `json:"id"`
	TaskId        string `json:"taskId"`
	CustomFieldId string `json:"customFieldId"`
	Value         []byte `json:"value"`
}

type Doc struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	SpaceID     pgtype.Text        `json:"space_id"`
	FolderID    pgtype.Text        `json:"folder_id"`
	ListID      pgtype.Text        `json:"list_id"`
	TaskID      pgtype.Text        `json:"task_id"`
	Title       string             `json:"title"`
	CreatedByID string             `json:"created_by_id"`
	IsPinned    bool               `json:"is_pinned"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DocComment struct {
	ID        string             `json:"id"`
	DocPageID string             `json:"doc_page_id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	ParentID  pgtype.Text        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DocPage struct {
	ID              string             `json:"id"`
	DocID           string             `json:"doc_id"`
	ParentPageID    pgtype.Text        `json:"parent_page_id"`
	Title           string             `json:"title"`
	ContentMarkdown string             `json:"content_markdown"`
	ContentHtml     string             `json:"content_html"`
	Icon            pgtype.Text        `json:"icon"`
	CoverImage      pgtype.Text        `json:"cover_image"`
	Position        float64            `json:"position"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsPublished     bool               `json:"is_published"`
	HasDraft        bool               `json:"has_draft"`
	DraftMarkdown   pgtype.Text        `json:"draft_markdown"`
	DraftHtml       pgtype.Text        `json:"draft_html"`
}

type Favorite struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
	ListId string `json:"listId"`
}

type Folder struct {
	ID        string           `json:"id"`
	SpaceId   string           `json:"spaceId"`
	Name      string           `json:"name"`
	Position  float64          `json:"position"`
	Collapsed bool             `json:"collapsed"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type List struct {
	ID        string           `json:"id"`
	SpaceId   string           `json:"spaceId"`
	FolderId  pgtype.Text      `json:"folderId"`
	Name      string           `json:"name"`
	Color     pgtype.Text      `json:"color"`
	Icon      pgtype.Text      `json:"icon"`
	Position  float64          `json:"position"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Notification struct {
	ID        string           `json:"id"`
	UserId    string           `json:"userId"`
	ActorId   pgtype.Text      `json:"actorId"`
	TaskId    pgtype.Text      `json:"taskId"`
	Type      string           `json:"type"`
	Body      string           `json:"body"`
	Read      bool             `json:"read"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type PrismaMigration struct {
	ID                string             `json:"id"`
	Checksum          string             `json:"checksum"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	MigrationName     string             `json:"migration_name"`
	Logs              pgtype.Text        `json:"logs"`
	RolledBackAt      pgtype.Timestamptz `json:"rolled_back_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	AppliedStepsCount int32              `json:"applied_steps_count"`
}

type Session struct {
	ID        string           `json:"id"`
	UserId    string           `json:"userId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Space struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	Name        string           `json:"name"`
	Color       string           `json:"color"`
	Icon        pgtype.Text      `json:"icon"`
	Private     bool             `json:"private"`
	Position    float64          `json:"position"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type Status struct {
	ID       string      `json:"id"`
	ListId   string      `json:"listId"`
	Name     string      `json:"name"`
	Color    string      `json:"color"`
	Type     StatusType  `json:"type"`
	Position float64     `json:"position"`
	WipLimit pgtype.Int4 `json:"wipLimit"`
}

type Tag struct {
	ID      string `json:"id"`
	SpaceId string `json:"spaceId"`
	Name    string `json:"name"`
	Color   string `json:"color"`
}

type Task struct {
	ID           string           `json:"id"`
	ListId       string           `json:"listId"`
	StatusId     string           `json:"statusId"`
	ParentId     pgtype.Text      `json:"parentId"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Priority     NullPriority     `json:"priority"`
	Position     float64          `json:"position"`
	StartDate    pgtype.Timestamp `json:"startDate"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	TimeEstimate pgtype.Int4      `json:"timeEstimate"`
	CreatedById  pgtype.Text      `json:"createdById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	Archived     bool             `json:"archived"`
	Recurrence   pgtype.Text      `json:"recurrence"`
}

type TaskAssignee struct {
	TaskId string `json:"taskId"`
	UserId string `json:"userId"`
}

type TaskDependency struct {
	ID        string           `json:"id"`
	BlockerId string           `json:"blockerId"`
	BlockedId string           `json:"blockedId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type TaskTag struct {
	TaskId string `json:"taskId"`
	TagId  string `json:"tagId"`
}

type TaskTemplate struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	Name        string           `json:"name"`
	TaskName    string           `json:"taskName"`
	Description pgtype.Text      `json:"description"`
	Priority    NullPriority     `json:"priority"`
	Checklists  []byte           `json:"checklists"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type TaskWatcher struct {
	TaskId string `json:"taskId"`
	UserId string `json:"userId"`
}

type TimeEntry struct {
	ID          string           `json:"id"`
	TaskId      string           `json:"taskId"`
	UserId      string           `json:"userId"`
	Duration    int32            `json:"duration"`
	Description pgtype.Text      `json:"description"`
	StartedAt   pgtype.Timestamp `json:"startedAt"`
	EndedAt     pgtype.Timestamp `json:"endedAt"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type User struct {
	ID           string           `json:"id"`
	Email        string           `json:"email"`
	Name         string           `json:"name"`
	Color        string           `json:"color"`
	AvatarUrl    pgtype.Text      `json:"avatarUrl"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	PasswordHash pgtype.Text      `json:"passwordHash"`
}

type View struct {
	ID       string   `json:"id"`
	ListId   string   `json:"listId"`
	Name     string   `json:"name"`
	Type     ViewType `json:"type"`
	Config   []byte   `json:"config"`
	Position float64  `json:"position"`
}

type Workspace struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Color     string           `json:"color"`
	AvatarUrl pgtype.Text      `json:"avatarUrl"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type WorkspaceMember struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	UserId      string           `json:"userId"`
	Role        MemberRole       `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}
