// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotificationsByUser = `-- name: CountUnreadNotificationsByUser :one
SELECT COUNT(*)::int
FROM "Notification"
WHERE "userId" = $1 AND read = false
`

func (q *Queries) CountUnreadNotificationsByUser(ctx context.Context, userid string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByUser, userid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT n.id, n."userId", n."actorId", n."taskId", n.type, n.body, n.read, n."createdAt",
       u.name as actor_name, u.email as actor_email, u.color as actor_color, u."avatarUrl" as actor_avatar_url,
       t.name as task_name, t."listId" as task_list_id
FROM "Notification" n
LEFT JOIN "User" u ON n."actorId" = u.id
LEFT JOIN "Task" t ON n."taskId" = t.id
WHERE n."userId" = $1
ORDER BY n."createdAt" DESC
LIMIT 50
`

type ListNotificationsByUserRow struct {
	ID             string           `json:"id"`
	UserId         string           `json:"userId"`
	ActorId        pgtype.Text      `json:"actorId"`
	TaskId         pgtype.Text      `json:"taskId"`
	Type           string           `json:"type"`
	Body           string           `json:"body"`
	Read           bool             `json:"read"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	ActorName      pgtype.Text      `json:"actor_name"`
	ActorEmail     pgtype.Text      `json:"actor_email"`
	ActorColor     pgtype.Text      `json:"actor_color"`
	ActorAvatarUrl pgtype.Text      `json:"actor_avatar_url"`
	TaskName       pgtype.Text      `json:"task_name"`
	TaskListID     pgtype.Text      `json:"task_list_id"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, userid string) ([]ListNotificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsByUserRow{}
	for rows.Next() {
		var i ListNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.ActorId,
			&i.TaskId,
			&i.Type,
			&i.Body,
			&i.Read,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
			&i.ActorColor,
			&i.ActorAvatarUrl,
			&i.TaskName,
			&i.TaskListID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE "Notification"
SET read = true
WHERE "userId" = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userid)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE "Notification"
SET read = true
WHERE "userId" = $1 AND id = ANY($2::text[])
`

type MarkNotificationsReadParams struct {
	UserId  string   `json:"userId"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserId, arg.Column2)
	return err
}
