// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStatus = `-- name: CreateStatus :one
INSERT INTO "Status" (id, "listId", name, color, type, "position", "wipLimit")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, "listId", name, color, type, "position", "wipLimit"
`

type CreateStatusParams struct {
	ID       string      `json:"id"`
	ListId   string      `json:"listId"`
	Name     string      `json:"name"`
	Color    string      `json:"color"`
	Type     StatusType  `json:"type"`
	Position float64     `json:"position"`
	WipLimit pgtype.Int4 `json:"wipLimit"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, createStatus,
		arg.ID,
		arg.ListId,
		arg.Name,
		arg.Color,
		arg.Type,
		arg.Position,
		arg.WipLimit,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.Name,
		&i.Color,
		&i.Type,
		&i.Position,
		&i.WipLimit,
	)
	return i, err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM "Status" WHERE id = $1
`

func (q *Queries) DeleteStatus(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteStatus, id)
	return err
}

const getStatusByID = `-- name: GetStatusByID :one
SELECT id, "listId", name, color, type, "position", "wipLimit"
FROM "Status"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStatusByID(ctx context.Context, id string) (Status, error) {
	row := q.db.QueryRow(ctx, getStatusByID, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.Name,
		&i.Color,
		&i.Type,
		&i.Position,
		&i.WipLimit,
	)
	return i, err
}

const listStatusesByList = `-- name: ListStatusesByList :many
SELECT id, "listId", name, color, type, "position", "wipLimit"
FROM "Status"
WHERE "listId" = $1
ORDER BY "position" ASC
`

func (q *Queries) ListStatusesByList(ctx context.Context, listid string) ([]Status, error) {
	rows, err := q.db.Query(ctx, listStatusesByList, listid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Status{}
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.ListId,
			&i.Name,
			&i.Color,
			&i.Type,
			&i.Position,
			&i.WipLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE "Status"
SET name = COALESCE($2, name),
    color = COALESCE($3, color),
    type = COALESCE($4, type),
    "position" = COALESCE($5, "position"),
    "wipLimit" = $6
WHERE id = $1
RETURNING id, "listId", name, color, type, "position", "wipLimit"
`

type UpdateStatusParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Color    string      `json:"color"`
	Type     StatusType  `json:"type"`
	Position float64     `json:"position"`
	WipLimit pgtype.Int4 `json:"wipLimit"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, updateStatus,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Type,
		arg.Position,
		arg.WipLimit,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.Name,
		&i.Color,
		&i.Type,
		&i.Position,
		&i.WipLimit,
	)
	return i, err
}
