// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskAssignee = `-- name: AddTaskAssignee :one
INSERT INTO "TaskAssignee" ("taskId", "userId")
VALUES ($1, $2)
ON CONFLICT ("taskId", "userId") DO NOTHING
RETURNING "taskId", "userId"
`

type AddTaskAssigneeParams struct {
	TaskId string `json:"taskId"`
	UserId string `json:"userId"`
}

func (q *Queries) AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) (TaskAssignee, error) {
	row := q.db.QueryRow(ctx, addTaskAssignee, arg.TaskId, arg.UserId)
	var i TaskAssignee
	err := row.Scan(&i.TaskId, &i.UserId)
	return i, err
}

const addTaskTag = `-- name: AddTaskTag :one
INSERT INTO "TaskTag" ("taskId", "tagId")
VALUES ($1, $2)
ON CONFLICT ("taskId", "tagId") DO NOTHING
RETURNING "taskId", "tagId"
`

type AddTaskTagParams struct {
	TaskId string `json:"taskId"`
	TagId  string `json:"tagId"`
}

func (q *Queries) AddTaskTag(ctx context.Context, arg AddTaskTagParams) (TaskTag, error) {
	row := q.db.QueryRow(ctx, addTaskTag, arg.TaskId, arg.TagId)
	var i TaskTag
	err := row.Scan(&i.TaskId, &i.TagId)
	return i, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO "Activity" (id, "taskId", "userId", type, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "taskId", "userId", type, data, "createdAt"
`

type CreateActivityParams struct {
	ID     string      `json:"id"`
	TaskId string      `json:"taskId"`
	UserId pgtype.Text `json:"userId"`
	Type   string      `json:"type"`
	Data   []byte      `json:"data"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.ID,
		arg.TaskId,
		arg.UserId,
		arg.Type,
		arg.Data,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.TaskId,
		&i.UserId,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO "Task" (id, "listId", "statusId", "parentId", name, description, priority, "position", "startDate", "dueDate", "timeEstimate", "createdById", "updatedAt", recurrence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), $13)
RETURNING id, "listId", "statusId", "parentId", name, description, priority, "position", "startDate", "dueDate", "timeEstimate", "createdById", "createdAt", "updatedAt", "completedAt", archived, recurrence
`

type CreateTaskParams struct {
	ID           string           `json:"id"`
	ListId       string           `json:"listId"`
	StatusId     string           `json:"statusId"`
	ParentId     pgtype.Text      `json:"parentId"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Priority     NullPriority     `json:"priority"`
	Position     float64          `json:"position"`
	StartDate    pgtype.Timestamp `json:"startDate"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	TimeEstimate pgtype.Int4      `json:"timeEstimate"`
	CreatedById  pgtype.Text      `json:"createdById"`
	Recurrence   pgtype.Text      `json:"recurrence"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.ListId,
		arg.StatusId,
		arg.ParentId,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.Position,
		arg.StartDate,
		arg.DueDate,
		arg.TimeEstimate,
		arg.CreatedById,
		arg.Recurrence,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.StatusId,
		&i.ParentId,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.StartDate,
		&i.DueDate,
		&i.TimeEstimate,
		&i.CreatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Archived,
		&i.Recurrence,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM "Task" WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t."listId", t."statusId", t."parentId", t.name, t.description, t.priority,
       t."position", t."startDate", t."dueDate", t."timeEstimate", t."createdById",
       t."createdAt", t."updatedAt", t."completedAt", t.archived, t.recurrence,
       s.name as status_name, s.color as status_color, s.type as status_type,
       l.name as list_name, sp.id as space_id, sp.name as space_name
FROM "Task" t
JOIN "Status" s ON t."statusId" = s.id
JOIN "List" l ON t."listId" = l.id
JOIN "Space" sp ON l."spaceId" = sp.id
WHERE t.id = $1 LIMIT 1
`

type GetTaskByIDRow struct {
	ID           string           `json:"id"`
	ListId       string           `json:"listId"`
	StatusId     string           `json:"statusId"`
	ParentId     pgtype.Text      `json:"parentId"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Priority     NullPriority     `json:"priority"`
	Position     float64          `json:"position"`
	StartDate    pgtype.Timestamp `json:"startDate"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	TimeEstimate pgtype.Int4      `json:"timeEstimate"`
	CreatedById  pgtype.Text      `json:"createdById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	Archived     bool             `json:"archived"`
	Recurrence   pgtype.Text      `json:"recurrence"`
	StatusName   string           `json:"status_name"`
	StatusColor  string           `json:"status_color"`
	StatusType   StatusType       `json:"status_type"`
	ListName     string           `json:"list_name"`
	SpaceID      string           `json:"space_id"`
	SpaceName    string           `json:"space_name"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id string) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.StatusId,
		&i.ParentId,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.StartDate,
		&i.DueDate,
		&i.TimeEstimate,
		&i.CreatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Archived,
		&i.Recurrence,
		&i.StatusName,
		&i.StatusColor,
		&i.StatusType,
		&i.ListName,
		&i.SpaceID,
		&i.SpaceName,
	)
	return i, err
}

const listActivitiesByTask = `-- name: ListActivitiesByTask :many
SELECT a.id, a."taskId", a."userId", a.type, a.data, a."createdAt",
       u.name as user_name, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "Activity" a
JOIN "User" u ON a."userId" = u.id
WHERE a."taskId" = $1
ORDER BY a."createdAt" DESC
`

type ListActivitiesByTaskRow struct {
	ID            string           `json:"id"`
	TaskId        string           `json:"taskId"`
	UserId        pgtype.Text      `json:"userId"`
	Type          string           `json:"type"`
	Data          []byte           `json:"data"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UserName      string           `json:"user_name"`
	UserColor     string           `json:"user_color"`
	UserAvatarUrl pgtype.Text      `json:"user_avatar_url"`
}

func (q *Queries) ListActivitiesByTask(ctx context.Context, taskid string) ([]ListActivitiesByTaskRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesByTask, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesByTaskRow{}
	for rows.Next() {
		var i ListActivitiesByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskId,
			&i.UserId,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.UserName,
			&i.UserColor,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTasks = `-- name: ListMyTasks :many
SELECT t.id, t.name, t."listId", t.priority, t."startDate", t."dueDate",
       s.name as status_name, s.color as status_color, s.type as status_type,
       l.name as list_name, sp.name as space_name, sp.color as space_color
FROM "Task" t
JOIN "TaskAssignee" ta ON t.id = ta."taskId"
JOIN "Status" s ON t."statusId" = s.id
JOIN "List" l ON t."listId" = l.id
JOIN "Space" sp ON l."spaceId" = sp.id
WHERE ta."userId" = $1 AND t.archived = false
ORDER BY t."dueDate" ASC NULLS LAST, t."createdAt" DESC
`

type ListMyTasksRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	ListId      string           `json:"listId"`
	Priority    NullPriority     `json:"priority"`
	StartDate   pgtype.Timestamp `json:"startDate"`
	DueDate     pgtype.Timestamp `json:"dueDate"`
	StatusName  string           `json:"status_name"`
	StatusColor string           `json:"status_color"`
	StatusType  StatusType       `json:"status_type"`
	ListName    string           `json:"list_name"`
	SpaceName   string           `json:"space_name"`
	SpaceColor  string           `json:"space_color"`
}

func (q *Queries) ListMyTasks(ctx context.Context, userid string) ([]ListMyTasksRow, error) {
	rows, err := q.db.Query(ctx, listMyTasks, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTasksRow{}
	for rows.Next() {
		var i ListMyTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListId,
			&i.Priority,
			&i.StartDate,
			&i.DueDate,
			&i.StatusName,
			&i.StatusColor,
			&i.StatusType,
			&i.ListName,
			&i.SpaceName,
			&i.SpaceColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasksByParent = `-- name: ListSubtasksByParent :many
SELECT t.id, t."listId", t."statusId", t."parentId", t.name, t.description, t.priority,
       t."position", t."startDate", t."dueDate", t."timeEstimate", t."createdById",
       t."createdAt", t."updatedAt", t."completedAt", t.archived, t.recurrence,
       s.name as status_name, s.color as status_color, s.type as status_type
FROM "Task" t
JOIN "Status" s ON t."statusId" = s.id
WHERE t."parentId" = $1 AND t.archived = false
ORDER BY t."position" ASC
`

type ListSubtasksByParentRow struct {
	ID           string           `json:"id"`
	ListId       string           `json:"listId"`
	StatusId     string           `json:"statusId"`
	ParentId     pgtype.Text      `json:"parentId"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Priority     NullPriority     `json:"priority"`
	Position     float64          `json:"position"`
	StartDate    pgtype.Timestamp `json:"startDate"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	TimeEstimate pgtype.Int4      `json:"timeEstimate"`
	CreatedById  pgtype.Text      `json:"createdById"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	Archived     bool             `json:"archived"`
	Recurrence   pgtype.Text      `json:"recurrence"`
	StatusName   string           `json:"status_name"`
	StatusColor  string           `json:"status_color"`
	StatusType   StatusType       `json:"status_type"`
}

func (q *Queries) ListSubtasksByParent(ctx context.Context, parentid pgtype.Text) ([]ListSubtasksByParentRow, error) {
	rows, err := q.db.Query(ctx, listSubtasksByParent, parentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubtasksByParentRow{}
	for rows.Next() {
		var i ListSubtasksByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ListId,
			&i.StatusId,
			&i.ParentId,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.Position,
			&i.StartDate,
			&i.DueDate,
			&i.TimeEstimate,
			&i.CreatedById,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Archived,
			&i.Recurrence,
			&i.StatusName,
			&i.StatusColor,
			&i.StatusType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT ta."taskId", ta."userId",
       u.name as user_name, u.email as user_email, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "TaskAssignee" ta
JOIN "User" u ON ta."userId" = u.id
WHERE ta."taskId" = $1
`

type ListTaskAssigneesRow struct {
	TaskId        string      `json:"taskId"`
	UserId        string      `json:"userId"`
	UserName      string      `json:"user_name"`
	UserEmail     string      `json:"user_email"`
	UserColor     string      `json:"user_color"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) ListTaskAssignees(ctx context.Context, taskid string) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAssigneesRow{}
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(
			&i.TaskId,
			&i.UserId,
			&i.UserName,
			&i.UserEmail,
			&i.UserColor,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAttachments = `-- name: ListTaskAttachments :many
SELECT a.id, a."taskId", a.name as file_name, a.size as file_size, a.mime as mime_type, a.url, a."createdAt"
FROM "Attachment" a
WHERE a."taskId" = $1
ORDER BY a."createdAt" DESC
`

type ListTaskAttachmentsRow struct {
	ID        string           `json:"id"`
	TaskId    string           `json:"taskId"`
	FileName  string           `json:"file_name"`
	FileSize  int32            `json:"file_size"`
	MimeType  string           `json:"mime_type"`
	Url       string           `json:"url"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListTaskAttachments(ctx context.Context, taskid string) ([]ListTaskAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskAttachments, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAttachmentsRow{}
	for rows.Next() {
		var i ListTaskAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskId,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskBlockedBy = `-- name: ListTaskBlockedBy :many
SELECT td.id, td."blockerId", td."blockedId",
       t.id as blocker_task_id, t.name as blocker_name, t."listId" as blocker_list_id,
       s.name as status_name, s.color as status_color, s.type as status_type
FROM "TaskDependency" td
JOIN "Task" t ON td."blockerId" = t.id
JOIN "Status" s ON t."statusId" = s.id
WHERE td."blockedId" = $1
`

type ListTaskBlockedByRow struct {
	ID            string     `json:"id"`
	BlockerId     string     `json:"blockerId"`
	BlockedId     string     `json:"blockedId"`
	BlockerTaskID string     `json:"blocker_task_id"`
	BlockerName   string     `json:"blocker_name"`
	BlockerListID string     `json:"blocker_list_id"`
	StatusName    string     `json:"status_name"`
	StatusColor   string     `json:"status_color"`
	StatusType    StatusType `json:"status_type"`
}

func (q *Queries) ListTaskBlockedBy(ctx context.Context, blockedid string) ([]ListTaskBlockedByRow, error) {
	rows, err := q.db.Query(ctx, listTaskBlockedBy, blockedid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskBlockedByRow{}
	for rows.Next() {
		var i ListTaskBlockedByRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockerId,
			&i.BlockedId,
			&i.BlockerTaskID,
			&i.BlockerName,
			&i.BlockerListID,
			&i.StatusName,
			&i.StatusColor,
			&i.StatusType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskBlocking = `-- name: ListTaskBlocking :many
SELECT td.id, td."blockerId", td."blockedId",
       t.id as blocked_task_id, t.name as blocked_name, t."listId" as blocked_list_id,
       s.name as status_name, s.color as status_color, s.type as status_type
FROM "TaskDependency" td
JOIN "Task" t ON td."blockedId" = t.id
JOIN "Status" s ON t."statusId" = s.id
WHERE td."blockerId" = $1
`

type ListTaskBlockingRow struct {
	ID            string     `json:"id"`
	BlockerId     string     `json:"blockerId"`
	BlockedId     string     `json:"blockedId"`
	BlockedTaskID string     `json:"blocked_task_id"`
	BlockedName   string     `json:"blocked_name"`
	BlockedListID string     `json:"blocked_list_id"`
	StatusName    string     `json:"status_name"`
	StatusColor   string     `json:"status_color"`
	StatusType    StatusType `json:"status_type"`
}

func (q *Queries) ListTaskBlocking(ctx context.Context, blockerid string) ([]ListTaskBlockingRow, error) {
	rows, err := q.db.Query(ctx, listTaskBlocking, blockerid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskBlockingRow{}
	for rows.Next() {
		var i ListTaskBlockingRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockerId,
			&i.BlockedId,
			&i.BlockedTaskID,
			&i.BlockedName,
			&i.BlockedListID,
			&i.StatusName,
			&i.StatusColor,
			&i.StatusType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTags = `-- name: ListTaskTags :many
SELECT tt."taskId", tt."tagId",
       tg.name as tag_name, tg.color as tag_color
FROM "TaskTag" tt
JOIN "Tag" tg ON tt."tagId" = tg.id
WHERE tt."taskId" = $1
`

type ListTaskTagsRow struct {
	TaskId   string `json:"taskId"`
	TagId    string `json:"tagId"`
	TagName  string `json:"tag_name"`
	TagColor string `json:"tag_color"`
}

func (q *Queries) ListTaskTags(ctx context.Context, taskid string) ([]ListTaskTagsRow, error) {
	rows, err := q.db.Query(ctx, listTaskTags, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskTagsRow{}
	for rows.Next() {
		var i ListTaskTagsRow
		if err := rows.Scan(
			&i.TaskId,
			&i.TagId,
			&i.TagName,
			&i.TagColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTimeEntries = `-- name: ListTaskTimeEntries :many
SELECT te.id, te."taskId", te."userId", te."startedAt", te."endedAt", te.duration,
       u.name as user_name, u.email as user_email, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "TimeEntry" te
JOIN "User" u ON te."userId" = u.id
WHERE te."taskId" = $1
ORDER BY te."startedAt" DESC
`

type ListTaskTimeEntriesRow struct {
	ID            string           `json:"id"`
	TaskId        string           `json:"taskId"`
	UserId        string           `json:"userId"`
	StartedAt     pgtype.Timestamp `json:"startedAt"`
	EndedAt       pgtype.Timestamp `json:"endedAt"`
	Duration      int32            `json:"duration"`
	UserName      string           `json:"user_name"`
	UserEmail     string           `json:"user_email"`
	UserColor     string           `json:"user_color"`
	UserAvatarUrl pgtype.Text      `json:"user_avatar_url"`
}

func (q *Queries) ListTaskTimeEntries(ctx context.Context, taskid string) ([]ListTaskTimeEntriesRow, error) {
	rows, err := q.db.Query(ctx, listTaskTimeEntries, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskTimeEntriesRow{}
	for rows.Next() {
		var i ListTaskTimeEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskId,
			&i.UserId,
			&i.StartedAt,
			&i.EndedAt,
			&i.Duration,
			&i.UserName,
			&i.UserEmail,
			&i.UserColor,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskWatchers = `-- name: ListTaskWatchers :many
SELECT tw."taskId", tw."userId",
       u.name as user_name, u.email as user_email, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "TaskWatcher" tw
JOIN "User" u ON tw."userId" = u.id
WHERE tw."taskId" = $1
`

type ListTaskWatchersRow struct {
	TaskId        string      `json:"taskId"`
	UserId        string      `json:"userId"`
	UserName      string      `json:"user_name"`
	UserEmail     string      `json:"user_email"`
	UserColor     string      `json:"user_color"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) ListTaskWatchers(ctx context.Context, taskid string) ([]ListTaskWatchersRow, error) {
	rows, err := q.db.Query(ctx, listTaskWatchers, taskid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskWatchersRow{}
	for rows.Next() {
		var i ListTaskWatchersRow
		if err := rows.Scan(
			&i.TaskId,
			&i.UserId,
			&i.UserName,
			&i.UserEmail,
			&i.UserColor,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByList = `-- name: ListTasksByList :many
SELECT t.id, t."listId", t."statusId", t."parentId", t.name, t.description, t.priority,
       t."position", t."startDate", t."dueDate", t."timeEstimate", t."createdById",
       t."createdAt", t."updatedAt", t."completedAt", t.archived, t.recurrence,
       s.name as status_name, s.color as status_color, s.type as status_type,
       (SELECT COUNT(*)::int FROM "Comment" c WHERE c."taskId" = t.id) as comment_count,
       (SELECT COUNT(*)::int FROM "Checklist" ch WHERE ch."taskId" = t.id) as checklist_count,
       (SELECT COUNT(*)::int FROM "Task" sub WHERE sub."parentId" = t.id AND sub.archived = false) as subtask_count
FROM "Task" t
JOIN "Status" s ON t."statusId" = s.id
WHERE t."listId" = $1 AND t."parentId" IS NULL AND t.archived = false
ORDER BY t."position" ASC
`

type ListTasksByListRow struct {
	ID             string           `json:"id"`
	ListId         string           `json:"listId"`
	StatusId       string           `json:"statusId"`
	ParentId       pgtype.Text      `json:"parentId"`
	Name           string           `json:"name"`
	Description    pgtype.Text      `json:"description"`
	Priority       NullPriority     `json:"priority"`
	Position       float64          `json:"position"`
	StartDate      pgtype.Timestamp `json:"startDate"`
	DueDate        pgtype.Timestamp `json:"dueDate"`
	TimeEstimate   pgtype.Int4      `json:"timeEstimate"`
	CreatedById    pgtype.Text      `json:"createdById"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	CompletedAt    pgtype.Timestamp `json:"completedAt"`
	Archived       bool             `json:"archived"`
	Recurrence     pgtype.Text      `json:"recurrence"`
	StatusName     string           `json:"status_name"`
	StatusColor    string           `json:"status_color"`
	StatusType     StatusType       `json:"status_type"`
	CommentCount   int32            `json:"comment_count"`
	ChecklistCount int32            `json:"checklist_count"`
	SubtaskCount   int32            `json:"subtask_count"`
}

func (q *Queries) ListTasksByList(ctx context.Context, listid string) ([]ListTasksByListRow, error) {
	rows, err := q.db.Query(ctx, listTasksByList, listid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByListRow{}
	for rows.Next() {
		var i ListTasksByListRow
		if err := rows.Scan(
			&i.ID,
			&i.ListId,
			&i.StatusId,
			&i.ParentId,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.Position,
			&i.StartDate,
			&i.DueDate,
			&i.TimeEstimate,
			&i.CreatedById,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Archived,
			&i.Recurrence,
			&i.StatusName,
			&i.StatusColor,
			&i.StatusType,
			&i.CommentCount,
			&i.ChecklistCount,
			&i.SubtaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskAssignee = `-- name: RemoveTaskAssignee :exec
DELETE FROM "TaskAssignee"
WHERE "taskId" = $1 AND "userId" = $2
`

type RemoveTaskAssigneeParams struct {
	TaskId string `json:"taskId"`
	UserId string `json:"userId"`
}

func (q *Queries) RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeTaskAssignee, arg.TaskId, arg.UserId)
	return err
}

const removeTaskTag = `-- name: RemoveTaskTag :exec
DELETE FROM "TaskTag"
WHERE "taskId" = $1 AND "tagId" = $2
`

type RemoveTaskTagParams struct {
	TaskId string `json:"taskId"`
	TagId  string `json:"tagId"`
}

func (q *Queries) RemoveTaskTag(ctx context.Context, arg RemoveTaskTagParams) error {
	_, err := q.db.Exec(ctx, removeTaskTag, arg.TaskId, arg.TagId)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE "Task"
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    priority = $4,
    "statusId" = COALESCE($5, "statusId"),
    "position" = COALESCE($6, "position"),
    "startDate" = $7,
    "dueDate" = $8,
    "timeEstimate" = $9,
    "completedAt" = $10,
    archived = COALESCE($11, archived),
    recurrence = $12,
    "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "listId", "statusId", "parentId", name, description, priority, "position", "startDate", "dueDate", "timeEstimate", "createdById", "createdAt", "updatedAt", "completedAt", archived, recurrence
`

type UpdateTaskParams struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Priority     NullPriority     `json:"priority"`
	StatusId     string           `json:"statusId"`
	Position     float64          `json:"position"`
	StartDate    pgtype.Timestamp `json:"startDate"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	TimeEstimate pgtype.Int4      `json:"timeEstimate"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	Archived     bool             `json:"archived"`
	Recurrence   pgtype.Text      `json:"recurrence"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.StatusId,
		arg.Position,
		arg.StartDate,
		arg.DueDate,
		arg.TimeEstimate,
		arg.CompletedAt,
		arg.Archived,
		arg.Recurrence,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.StatusId,
		&i.ParentId,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.StartDate,
		&i.DueDate,
		&i.TimeEstimate,
		&i.CreatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Archived,
		&i.Recurrence,
	)
	return i, err
}
