// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package db

import (
	"context"
)

const createView = `-- name: CreateView :one
INSERT INTO "View" (id, "listId", name, type, config, "position")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, "listId", name, type, config, "position"
`

type CreateViewParams struct {
	ID       string   `json:"id"`
	ListId   string   `json:"listId"`
	Name     string   `json:"name"`
	Type     ViewType `json:"type"`
	Config   []byte   `json:"config"`
	Position float64  `json:"position"`
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRow(ctx, createView,
		arg.ID,
		arg.ListId,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Position,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Position,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM "View" WHERE id = $1
`

func (q *Queries) DeleteView(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteView, id)
	return err
}

const getViewByID = `-- name: GetViewByID :one
SELECT id, "listId", name, type, config, "position"
FROM "View"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetViewByID(ctx context.Context, id string) (View, error) {
	row := q.db.QueryRow(ctx, getViewByID, id)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Position,
	)
	return i, err
}

const listViewsByList = `-- name: ListViewsByList :many
SELECT id, "listId", name, type, config, "position"
FROM "View"
WHERE "listId" = $1
ORDER BY "position" ASC
`

func (q *Queries) ListViewsByList(ctx context.Context, listid string) ([]View, error) {
	rows, err := q.db.Query(ctx, listViewsByList, listid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []View{}
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.ListId,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateViewConfig = `-- name: UpdateViewConfig :one
UPDATE "View"
SET config = $2
WHERE id = $1
RETURNING id, "listId", name, type, config, "position"
`

type UpdateViewConfigParams struct {
	ID     string `json:"id"`
	Config []byte `json:"config"`
}

func (q *Queries) UpdateViewConfig(ctx context.Context, arg UpdateViewConfigParams) (View, error) {
	row := q.db.QueryRow(ctx, updateViewConfig, arg.ID, arg.Config)
	var i View
	err := row.Scan(
		&i.ID,
		&i.ListId,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Position,
	)
	return i, err
}
