// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :one
INSERT INTO "Favorite" (id, "userId", "listId")
VALUES ($1, $2, $3)
ON CONFLICT ("userId", "listId") DO NOTHING
RETURNING id, "userId", "listId"
`

type AddFavoriteParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
	ListId string `json:"listId"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, addFavorite, arg.ID, arg.UserId, arg.ListId)
	var i Favorite
	err := row.Scan(&i.ID, &i.UserId, &i.ListId)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO "Folder" (id, "spaceId", name, "position", collapsed)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "spaceId", name, "position", collapsed, "createdAt"
`

type CreateFolderParams struct {
	ID        string  `json:"id"`
	SpaceId   string  `json:"spaceId"`
	Name      string  `json:"name"`
	Position  float64 `json:"position"`
	Collapsed bool    `json:"collapsed"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.SpaceId,
		arg.Name,
		arg.Position,
		arg.Collapsed,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceId,
		&i.Name,
		&i.Position,
		&i.Collapsed,
		&i.CreatedAt,
	)
	return i, err
}

const createList = `-- name: CreateList :one
INSERT INTO "List" (id, "spaceId", "folderId", name, color, icon, "position")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, "spaceId", "folderId", name, color, icon, "position", "createdAt"
`

type CreateListParams struct {
	ID       string      `json:"id"`
	SpaceId  string      `json:"spaceId"`
	FolderId pgtype.Text `json:"folderId"`
	Name     string      `json:"name"`
	Color    pgtype.Text `json:"color"`
	Icon     pgtype.Text `json:"icon"`
	Position float64     `json:"position"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.ID,
		arg.SpaceId,
		arg.FolderId,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.Position,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.SpaceId,
		&i.FolderId,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO "Space" (id, "workspaceId", name, color, icon, private, "position")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, "workspaceId", name, color, icon, private, "position", "createdAt"
`

type CreateSpaceParams struct {
	ID          string      `json:"id"`
	WorkspaceId string      `json:"workspaceId"`
	Name        string      `json:"name"`
	Color       string      `json:"color"`
	Icon        pgtype.Text `json:"icon"`
	Private     bool        `json:"private"`
	Position    float64     `json:"position"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.ID,
		arg.WorkspaceId,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.Private,
		arg.Position,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Private,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO "Workspace" (id, name, color, "avatarUrl")
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, "avatarUrl", "createdAt"
`

type CreateWorkspaceParams struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	AvatarUrl pgtype.Text `json:"avatarUrl"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.AvatarUrl,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO "WorkspaceMember" (id, "workspaceId", "userId", role)
VALUES ($1, $2, $3, $4)
RETURNING id, "workspaceId", "userId", role, "createdAt"
`

type CreateWorkspaceMemberParams struct {
	ID          string     `json:"id"`
	WorkspaceId string     `json:"workspaceId"`
	UserId      string     `json:"userId"`
	Role        MemberRole `json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember,
		arg.ID,
		arg.WorkspaceId,
		arg.UserId,
		arg.Role,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.UserId,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM "Folder" WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM "List" WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM "Space" WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getFirstWorkspace = `-- name: GetFirstWorkspace :one
SELECT id, name, color, "avatarUrl", "createdAt"
FROM "Workspace"
ORDER BY "createdAt" ASC
LIMIT 1
`

func (q *Queries) GetFirstWorkspace(ctx context.Context) (Workspace, error) {
	row := q.db.QueryRow(ctx, getFirstWorkspace)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getListByID = `-- name: GetListByID :one
SELECT l.id, l."spaceId", l."folderId", l.name, l.color, l.icon, l."position", l."createdAt",
       s.name as space_name, s.color as space_color, s.icon as space_icon,
       f.name as folder_name
FROM "List" l
JOIN "Space" s ON l."spaceId" = s.id
LEFT JOIN "Folder" f ON l."folderId" = f.id
WHERE l.id = $1 LIMIT 1
`

type GetListByIDRow struct {
	ID         string           `json:"id"`
	SpaceId    string           `json:"spaceId"`
	FolderId   pgtype.Text      `json:"folderId"`
	Name       string           `json:"name"`
	Color      pgtype.Text      `json:"color"`
	Icon       pgtype.Text      `json:"icon"`
	Position   float64          `json:"position"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	SpaceName  string           `json:"space_name"`
	SpaceColor string           `json:"space_color"`
	SpaceIcon  pgtype.Text      `json:"space_icon"`
	FolderName pgtype.Text      `json:"folder_name"`
}

func (q *Queries) GetListByID(ctx context.Context, id string) (GetListByIDRow, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i GetListByIDRow
	err := row.Scan(
		&i.ID,
		&i.SpaceId,
		&i.FolderId,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
		&i.SpaceName,
		&i.SpaceColor,
		&i.SpaceIcon,
		&i.FolderName,
	)
	return i, err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, "workspaceId", name, color, icon, private, "position", "createdAt"
FROM "Space"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Private,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listFoldersBySpace = `-- name: ListFoldersBySpace :many
SELECT id, "spaceId", name, "position", collapsed, "createdAt"
FROM "Folder"
WHERE "spaceId" = $1
ORDER BY "position" ASC
`

func (q *Queries) ListFoldersBySpace(ctx context.Context, spaceid string) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersBySpace, spaceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceId,
			&i.Name,
			&i.Position,
			&i.Collapsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListsBySpace = `-- name: ListListsBySpace :many
SELECT l.id, l."spaceId", l."folderId", l.name, l.color, l.icon, l."position", l."createdAt",
       COUNT(t.id)::int as task_count
FROM "List" l
LEFT JOIN "Task" t ON t."listId" = l.id AND t.archived = false
WHERE l."spaceId" = $1
GROUP BY l.id
ORDER BY l."position" ASC
`

type ListListsBySpaceRow struct {
	ID        string           `json:"id"`
	SpaceId   string           `json:"spaceId"`
	FolderId  pgtype.Text      `json:"folderId"`
	Name      string           `json:"name"`
	Color     pgtype.Text      `json:"color"`
	Icon      pgtype.Text      `json:"icon"`
	Position  float64          `json:"position"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	TaskCount int32            `json:"task_count"`
}

func (q *Queries) ListListsBySpace(ctx context.Context, spaceid string) ([]ListListsBySpaceRow, error) {
	rows, err := q.db.Query(ctx, listListsBySpace, spaceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListsBySpaceRow{}
	for rows.Next() {
		var i ListListsBySpaceRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceId,
			&i.FolderId,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByWorkspace = `-- name: ListSpacesByWorkspace :many
SELECT id, "workspaceId", name, color, icon, private, "position", "createdAt"
FROM "Space"
WHERE "workspaceId" = $1
ORDER BY "position" ASC
`

func (q *Queries) ListSpacesByWorkspace(ctx context.Context, workspaceid string) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByWorkspace, workspaceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceId,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.Private,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFavorites = `-- name: ListUserFavorites :many
SELECT "listId" FROM "Favorite"
WHERE "userId" = $1
`

func (q *Queries) ListUserFavorites(ctx context.Context, userid string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserFavorites, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var listId string
		if err := rows.Scan(&listId); err != nil {
			return nil, err
		}
		items = append(items, listId)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.id, wm."workspaceId", wm."userId", wm.role, wm."createdAt",
       u.name as user_name, u.email as user_email, u.color as user_color, u."avatarUrl" as user_avatar_url
FROM "WorkspaceMember" wm
JOIN "User" u ON wm."userId" = u.id
WHERE wm."workspaceId" = $1
ORDER BY wm."createdAt" ASC
`

type ListWorkspaceMembersRow struct {
	ID            string           `json:"id"`
	WorkspaceId   string           `json:"workspaceId"`
	UserId        string           `json:"userId"`
	Role          MemberRole       `json:"role"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UserName      string           `json:"user_name"`
	UserEmail     string           `json:"user_email"`
	UserColor     string           `json:"user_color"`
	UserAvatarUrl pgtype.Text      `json:"user_avatar_url"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceid string) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceId,
			&i.UserId,
			&i.Role,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserColor,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM "Favorite"
WHERE "userId" = $1 AND "listId" = $2
`

type RemoveFavoriteParams struct {
	UserId string `json:"userId"`
	ListId string `json:"listId"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserId, arg.ListId)
	return err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE "Folder"
SET name = COALESCE($2, name)
WHERE id = $1
RETURNING id, "spaceId", name, "position", collapsed, "createdAt"
`

type UpdateFolderParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceId,
		&i.Name,
		&i.Position,
		&i.Collapsed,
		&i.CreatedAt,
	)
	return i, err
}

const updateList = `-- name: UpdateList :one
UPDATE "List"
SET name = COALESCE($2, name),
    color = COALESCE($3, color)
WHERE id = $1
RETURNING id, "spaceId", "folderId", name, color, icon, "position", "createdAt"
`

type UpdateListParams struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList, arg.ID, arg.Name, arg.Color)
	var i List
	err := row.Scan(
		&i.ID,
		&i.SpaceId,
		&i.FolderId,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE "Space"
SET name = COALESCE($2, name),
    color = COALESCE($3, color),
    icon = COALESCE($4, icon)
WHERE id = $1
RETURNING id, "workspaceId", name, color, icon, private, "position", "createdAt"
`

type UpdateSpaceParams struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Color string      `json:"color"`
	Icon  pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.Private,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
